### ISSUE TITLE
`build.py` watch mode regularly crashes due to dangling symlinks

### ISSUE THREAD

**Issue by nexushoratio** [IITC-CE/ingress-intel-total-conversion#788]
I'm regularly seeing the following due to disappearing emacs autosave files.
```
Traceback (most recent call last):
  File "/home/nexus/src/ingress-intel-total-conversion-git/./build.py", line 141, in watch
    build_cb(*args, deps_list=watch_list, **kwargs)
  File "/home/nexus/src/ingress-intel-total-conversion-git/./build.py", line 88, in backup_and_run
    iitc_build(source, workdir, deps_list=deps_list)
  File "/home/nexus/src/ingress-intel-total-conversion-git/./build.py", line 55, in iitc_build
    build_plugin.process_file(source / iitc_script, outdir, deps_list=deps_list)
  File "/home/nexus/src/ingress-intel-total-conversion-git/build_plugin.py", line 184, in process_file
    script = re.sub(r"'@bundle_code@';", partial(bundle_code, path=path), script)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nexus/src/ingress-intel-total-conversion-git/build_plugin.py", line 133, in bundle_code
    return '\n'.join(map(wrap_iife, sorted(files)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nexus/src/ingress-intel-total-conversion-git/build_plugin.py", line 128, in wrap_iife
    """.format(filename, filename, content=readtext(filename))
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/nexus/src/ingress-intel-total-conversion-git/build_plugin.py", line 103, in readtext
    return filename.read_text(encoding='utf-8-sig')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'core/code/.#map_data_render.js'
```

**Comment by nexushoratio** [comment]
Ahh, it doesn't like dangling symlinks.
